spring:

  datasource:
    url: jdbc:sqlserver://alt-server.database.windows.net:1433;database=demoDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sirajularfin
    password: admin@123
     
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9090
  